// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/proto/gateway.proto

package gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoomServerGateway_Channel_FullMethodName = "/imsys.RoomServerGateway/Channel"
)

// RoomServerGatewayClient is the client API for RoomServerGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gateway 与 Roomserver 之间的双向流通信
type RoomServerGatewayClient interface {
	// 双向流：Gateway 和 Roomserver 之间的长连接通道
	Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type roomServerGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServerGatewayClient(cc grpc.ClientConnInterface) RoomServerGatewayClient {
	return &roomServerGatewayClient{cc}
}

func (c *roomServerGatewayClient) Channel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RoomServerGateway_ServiceDesc.Streams[0], RoomServerGateway_Channel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomServerGateway_ChannelClient = grpc.BidiStreamingClient[Envelope, Envelope]

// RoomServerGatewayServer is the server API for RoomServerGateway service.
// All implementations must embed UnimplementedRoomServerGatewayServer
// for forward compatibility.
//
// Gateway 与 Roomserver 之间的双向流通信
type RoomServerGatewayServer interface {
	// 双向流：Gateway 和 Roomserver 之间的长连接通道
	Channel(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedRoomServerGatewayServer()
}

// UnimplementedRoomServerGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServerGatewayServer struct{}

func (UnimplementedRoomServerGatewayServer) Channel(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Error(codes.Unimplemented, "method Channel not implemented")
}
func (UnimplementedRoomServerGatewayServer) mustEmbedUnimplementedRoomServerGatewayServer() {}
func (UnimplementedRoomServerGatewayServer) testEmbeddedByValue()                           {}

// UnsafeRoomServerGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServerGatewayServer will
// result in compilation errors.
type UnsafeRoomServerGatewayServer interface {
	mustEmbedUnimplementedRoomServerGatewayServer()
}

func RegisterRoomServerGatewayServer(s grpc.ServiceRegistrar, srv RoomServerGatewayServer) {
	// If the following call panics, it indicates UnimplementedRoomServerGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomServerGateway_ServiceDesc, srv)
}

func _RoomServerGateway_Channel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RoomServerGatewayServer).Channel(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RoomServerGateway_ChannelServer = grpc.BidiStreamingServer[Envelope, Envelope]

// RoomServerGateway_ServiceDesc is the grpc.ServiceDesc for RoomServerGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomServerGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imsys.RoomServerGateway",
	HandlerType: (*RoomServerGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Channel",
			Handler:       _RoomServerGateway_Channel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/gateway.proto",
}

const (
	RoomServerInternal_Forward_FullMethodName = "/imsys.RoomServerInternal/Forward"
)

// RoomServerInternalClient is the client API for RoomServerInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Roomserver 之间的内部通信（用于请求转发）
type RoomServerInternalClient interface {
	// 转发推送请求（路由过时时使用）
	Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
}

type roomServerInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewRoomServerInternalClient(cc grpc.ClientConnInterface) RoomServerInternalClient {
	return &roomServerInternalClient{cc}
}

func (c *roomServerInternalClient) Forward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, RoomServerInternal_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoomServerInternalServer is the server API for RoomServerInternal service.
// All implementations must embed UnimplementedRoomServerInternalServer
// for forward compatibility.
//
// Roomserver 之间的内部通信（用于请求转发）
type RoomServerInternalServer interface {
	// 转发推送请求（路由过时时使用）
	Forward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	mustEmbedUnimplementedRoomServerInternalServer()
}

// UnimplementedRoomServerInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoomServerInternalServer struct{}

func (UnimplementedRoomServerInternalServer) Forward(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedRoomServerInternalServer) mustEmbedUnimplementedRoomServerInternalServer() {}
func (UnimplementedRoomServerInternalServer) testEmbeddedByValue()                            {}

// UnsafeRoomServerInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoomServerInternalServer will
// result in compilation errors.
type UnsafeRoomServerInternalServer interface {
	mustEmbedUnimplementedRoomServerInternalServer()
}

func RegisterRoomServerInternalServer(s grpc.ServiceRegistrar, srv RoomServerInternalServer) {
	// If the following call panics, it indicates UnimplementedRoomServerInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoomServerInternal_ServiceDesc, srv)
}

func _RoomServerInternal_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoomServerInternalServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoomServerInternal_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoomServerInternalServer).Forward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoomServerInternal_ServiceDesc is the grpc.ServiceDesc for RoomServerInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoomServerInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "imsys.RoomServerInternal",
	HandlerType: (*RoomServerInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _RoomServerInternal_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/gateway.proto",
}
